revert

diff --git a/.github/workflows/build-pr-preview.yml b/.github/workflows/build-pr-preview.yml
--- a/.github/workflows/build-pr-preview.yml
+++ b/.github/workflows/build-pr-preview.yml
@@ -4,9 +4,6 @@ run-name: 'Build Preview for "${{ github.event.pull_request.title }}" (#${{ gith
 on:
   pull_request_target:
     types: [opened, synchronize]
-  push: 
-    branches:
-      - 'leah/fix/link-checker-fail-if-empty-false'
   # Hello Security 👋, we are checking to make sure forked repo PR changed paths are only in content/** inside the job security-check.
   # We are doing this so we can also reuse this workflow for internal PRs, as pull_request_target also triggers on internal PRs. (As does pull_request)
 
@@ -45,32 +42,32 @@ jobs:
           base_sha: ${{ github.event.pull_request.base.sha }}
           sha: ${{ github.event.pull_request.head.sha }}
 
-  # security-check:
-  #   name: Security Check
-  #   runs-on: ubuntu-latest
-  #   needs: [get-changed-files]
-  #   steps:
-  #     - name: If in a forked repo fail if any changes are outside of content/**
-  #       run: |
-  #         : # Cases:
-  #         : # 1. PR from forked repo, changes outside of content/**; fail
-  #         if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ] && [ ${{ needs.get-changed-files.outputs.not_content_bad_boy_naughty_files_count }} -gt 0 ]; then
+  security-check:
+    name: Security Check
+    runs-on: ubuntu-latest
+    needs: [get-changed-files]
+    steps:
+      - name: If in a forked repo fail if any changes are outside of content/**
+        run: |
+          : # Cases:
+          : # 1. PR from forked repo, changes outside of content/**; fail
+          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ] && [ ${{ needs.get-changed-files.outputs.not_content_bad_boy_naughty_files_count }} -gt 0 ]; then
 
-  #           echo "❌ This is a PR from a forked repo with changes outside of content/\*\*. **Please only edit files in the content/\*\* directory.**" >> $GITHUB_STEP_SUMMARY
-  #           exit 1
+            echo "❌ This is a PR from a forked repo with changes outside of content/\*\*. **Please only edit files in the content/\*\* directory.**" >> $GITHUB_STEP_SUMMARY
+            exit 1
 
-  #         : # 2. PR from forked repo, changes only in content/**; pass
-  #         elif [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ] && [ ${{ needs.get-changed-files.outputs.not_content_bad_boy_naughty_files_count }} -eq 0 ]; then
+          : # 2. PR from forked repo, changes only in content/**; pass
+          elif [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ] && [ ${{ needs.get-changed-files.outputs.not_content_bad_boy_naughty_files_count }} -eq 0 ]; then
 
-  #           echo "✅ This is a PR from a forked repo with NO changes outside of content/\*\*. Proceeding with the workflow." >> $GITHUB_STEP_SUMMARY
-  #           exit 0
+            echo "✅ This is a PR from a forked repo with NO changes outside of content/\*\*. Proceeding with the workflow." >> $GITHUB_STEP_SUMMARY
+            exit 0
 
-  #         fi
+          fi
 
-  #         : # 3. PR from internal repo, changes outside of content/**; pass
-  #         : # 4. PR from internal repo, changes only in content/**; pass
-  #         echo "✅ This is an internal PR. Proceeding with the workflow." >> $GITHUB_STEP_SUMMARY
-  #         exit 0
+          : # 3. PR from internal repo, changes outside of content/**; pass
+          : # 4. PR from internal repo, changes only in content/**; pass
+          echo "✅ This is an internal PR. Proceeding with the workflow." >> $GITHUB_STEP_SUMMARY
+          exit 0
 
   deploy-unified-docs-api-preview:
     name: Deploy Unified Docs API Preview
