Add some more security checks

diff --git a/.github/workflows/build-pr-preview.yml b/.github/workflows/build-pr-preview.yml
--- a/.github/workflows/build-pr-preview.yml
+++ b/.github/workflows/build-pr-preview.yml
@@ -264,8 +264,16 @@ jobs:
           PR_BODY: ${{ github.event.pull_request.body }}
         run: |
           # e.g. /set-env USE_DEV_PORTAL_REF=rn/test-UDR-target
+          # grab the value until the first whitespace
           EXTRACTED_VAL=$(echo "$PR_BODY" | grep -oP '(?<=USE_DEV_PORTAL_REF=)[^[:space:]]+')
-          echo "USE_DEV_PORTAL_REF=$EXTRACTED_VAL" >> $GITHUB_ENV
+
+          # Only allow safe git-ref style characters.
+          if [[ -n "$EXTRACTED_VAL" && "$EXTRACTED_VAL" =~ ^[A-Za-z0-9._/-]+$ ]]; then
+            echo "USE_DEV_PORTAL_REF=$EXTRACTED_VAL" >> $GITHUB_ENV
+          else
+            echo "Invalid USE_DEV_PORTAL_REF." >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
 
       - name: Checkout hashicorp/dev-portal (Frontend)
         uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
